import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <form name="contact" method="POST" data-netlify="true" hidden>
          <label>
            Your Name:
            <input type="text" name="name" />
          </label>
          <label>
            Your Email:
            <input type="email" name="email" />
          </label>
          <label>
            Message: <textarea name="message"></textarea>
          </label>
          <button type="submit">Send</button>
        </form>
      </body>
    </html>
  );
}
